# Generated by Django 6.0.4 on 2026-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='codigo_registro',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
